Repository Sitecore/ASP.NET-Core-SDK, pull requests merged in 2024-08, with the labels that each got.

#2 Fix pages release permissions issue
  .github/workflows/main.yml
Labels: bug

#3 Fix pages write permission missing
  .github/workflows/main.yml
Labels: bug

#4 Small docfx docs improvements.
  docfx/index.md
  docfx/overview/index.md
Labels: documentation

#5 Fixed Integration Test for Component and Route property binding
  tests/Sitecore.AspNetCore.SDK.RenderingEngine.Integration.Tests/Fixtures/Binding/ComplexModelBindingFixture.cs
  tests/Sitecore.AspNetCore.SDK.RenderingEngine.Integration.Tests/Views/Shared/Components/SitecoreComponent/ComplexComponent.cshtml
Labels: bug

#6 Fixed issue rendering nested empty placeholders
  src/Sitecore.AspNetCore.SDK.RenderingEngine/TagHelpers/PlaceholderTagHelper.cs
  tests/Sitecore.AspNetCore.SDK.RenderingEngine.Tests/TagHelpers/PlaceholderTagHelperFixture.cs
Labels: bug

#7 Improved Build Summary
  .github/workflows/TestSummary.ps1
  .github/workflows/Version.ps1
  .github/workflows/build.yml
  Sitecore.AspNetCore.SDK.sln
  tests/Sitecore.AspNetCore.SDK.AutoFixture/ActionProviders/SetupActionsProvider.cs
  tests/Sitecore.AspNetCore.SDK.AutoFixture/ActionProviders/StaticMethodSetupActionsProvider.cs
  tests/Sitecore.AspNetCore.SDK.AutoFixture/ActionProviders/StaticPropertySetupActionsProvider.cs
  tests/Sitecore.AspNetCore.SDK.AutoFixture/Attributes/AutoNSubstituteDataAttribute.cs
  tests/Sitecore.AspNetCore.SDK.AutoFixture/Attributes/AutoSetupDataAttribute.cs
  tests/Sitecore.AspNetCore.SDK.AutoFixture/Attributes/InlineAutoNSubstituteDataAttribute.cs
  tests/Sitecore.AspNetCore.SDK.AutoFixture/Attributes/InlineAutoSetupDataAttribute.cs
  tests/Sitecore.AspNetCore.SDK.AutoFixture/Attributes/MemberAutoNSubstituteDataAttribute.cs
  tests/Sitecore.AspNetCore.SDK.AutoFixture/Attributes/MemberAutoSetupDataAttribute.cs
  tests/Sitecore.AspNetCore.SDK.AutoFixture/Extensions/GuardClauseAssertionExtensions.cs
  tests/data/Sitecore.AspNetCore.SDK.TestData/CannedResponses.cs
  tests/data/Sitecore.AspNetCore.SDK.TestData/Models/CustomFieldType.cs
  tests/data/Sitecore.AspNetCore.SDK.TestData/Serializer.cs
  tests/data/Sitecore.AspNetCore.SDK.TestData/TestConstants.cs
Labels: enhancement

#9 Add GetRawValue() to return raw JSON in JsonSerializedField.
  src/Sitecore.AspNetCore.SDK.LayoutService.Client/Serialization/Fields/JsonSerializedField.cs
  tests/Sitecore.AspNetCore.SDK.LayoutService.Client.Tests/Serialization/Fields/JsonSerializedFieldTests.cs
Labels: enhancement
